kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/terragrunt
    build_args:
    - TERRAFORM_VERSION=0.14.10
    - TERRAGRUNT_VERSION=0.28.24
    tags:
    - latest
    - "0.28.24_tf0.14.10"
    - "0.28_tf0.14.10"

trigger:
  event:
  - push
  branch:
  - master
